/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appabsensismpihidayatuttholibin.view.popupTambah;

import appabsensismpihidayatuttholibin.Config.Koneksi;
import appabsensismpihidayatuttholibin.view.mainPanel.panelPergantianGuru;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JPanel;

import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class tambahPergantianGuru extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tambahPergantianGuru.class.getName());
    private panelPergantianGuru pPerG;
    
    /**
     * Creates new form tambahPergantianGuru
     */
    public tambahPergantianGuru(java.awt.Frame parent, boolean modal, panelPergantianGuru pPerG) {
        super(parent, modal);
        initComponents();
        
        //supaya JDialognya tranparan jadi roundnya jadi kelihatan dehh
        this.setBackground(new Color(0, 0, 0, 0));
        if (this.getContentPane() instanceof javax.swing.JComponent) {
            ((javax.swing.JComponent) this.getContentPane()).setOpaque(false);
        }
        
        borderLengkung(panelUtama, "#828282");
        
        this.pPerG = pPerG;
        
        tampil_combobox();
        
        generateIdPergantian();
        
        tID.setEditable(false);
        tID.setFocusable(false);

        java.awt.EventQueue.invokeLater(() -> {
            jTGL.requestFocusInWindow();
        });
    }
    
    // membuat method bersih untuk tcari yang apabila diklik tulisan akan hilang
    void bersih(){
        tID.setText("ID Pengguna");
        tMapel.setText("Mapel");
        tJamke.setText("Jam ke");
    }
    
    //method untuk custom panel supaya ada roundnya dan bordernya
    void borderLengkung(JPanel panel, String hexColor) {
        panel.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0),
                Color.decode(hexColor),
                2f,
                20
        ));
    }

    void tampil_combobox() {
        try {
            java.sql.Connection conn = Koneksi.konek();
            java.sql.Statement st = conn.createStatement();

            String sql = "SELECT nama_guru FROM guru";
            java.sql.ResultSet rs = st.executeQuery(sql);

            cbNamaGuru.removeAllItems();
            cbGuruPengganti.removeAllItems();

            while (rs.next()) {
                String nama = rs.getString("nama_guru");
                cbNamaGuru.addItem(nama);
                cbGuruPengganti.addItem(nama);
            }

        } catch (SQLException e) {
            System.out.println("Gagal load combobox: " + e.getMessage());
        }
        cbNamaGuru.setSelectedItem(null);
        cbGuruPengganti.setSelectedItem(null);
    }
    
    private String cariNip(String namaGuru) {
        String idDitemukan = "";
        try {
            java.sql.Connection conn = Koneksi.konek();
            String sql = "SELECT id_guru FROM guru WHERE nama_guru = ?";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, namaGuru);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                idDitemukan = rs.getString("id_guru");
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Gagal mencari NIP: " + e.getMessage());
        }
        return idDitemukan;
    }
    
    private void generateIdPergantian() {
        try {
            Connection conn = Koneksi.konek();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_pergantianguru FROM pergantian_guru ORDER BY id_pergantianguru DESC LIMIT 1");
            
            if(rs.next()) {
                //ambil angka setelah ABS
                String id = rs.getString("id_pergantianguru").substring(3);
                int no = Integer.parseInt(id) + 1;
                
                tID.setText(String.format("PRG%03d", no));
            }else{
                tID.setText("PRG001");
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal generate ID : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        bSimpan = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tID = new javax.swing.JTextField();
        cbNamaGuru = new javax.swing.JComboBox<>();
        jTGL = new com.toedter.calendar.JDateChooser();
        tMapel = new javax.swing.JTextField();
        tJamke = new javax.swing.JTextField();
        cbGuruPengganti = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tKeterangan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tMateri = new javax.swing.JTextArea();
        lClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelUtama.setBackground(new java.awt.Color(229, 234, 239));

        jPanel1.setBackground(new java.awt.Color(229, 234, 239));

        jPanel2.setBackground(new java.awt.Color(229, 234, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(458, 80));

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel7.setText("Tambah Pergantian Guru");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(229, 234, 239));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(458, 80));

        jPanel8.setBackground(new java.awt.Color(229, 234, 239));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        bSimpan.setBackground(new java.awt.Color(0, 116, 188));
        bSimpan.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(this::bSimpanActionPerformed);
        jPanel8.add(bSimpan);

        bBatal.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(this::bBatalActionPerformed);
        jPanel8.add(bBatal);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(229, 234, 239));

        jPanel6.setBackground(new java.awt.Color(229, 234, 239));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID Pergantian");
        jLabel1.setPreferredSize(new java.awt.Dimension(37, 35));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tanggal");
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 35));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Guru Pengganti");
        jLabel3.setPreferredSize(new java.awt.Dimension(37, 35));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mapel");
        jLabel4.setPreferredSize(new java.awt.Dimension(37, 35));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Jam ke");
        jLabel5.setPreferredSize(new java.awt.Dimension(37, 35));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tugas/Materi yang diberikan");
        jLabel6.setPreferredSize(new java.awt.Dimension(37, 35));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nama Guru");
        jLabel8.setPreferredSize(new java.awt.Dimension(37, 35));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Keterangan");
        jLabel9.setPreferredSize(new java.awt.Dimension(37, 35));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(229, 234, 239));

        tID.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tID.setText("ID Pergantian");
        tID.setPreferredSize(new java.awt.Dimension(71, 35));
        tID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tIDFocusLost(evt);
            }
        });

        cbNamaGuru.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        cbNamaGuru.setPreferredSize(new java.awt.Dimension(72, 35));

        jTGL.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jTGL.setPreferredSize(new java.awt.Dimension(85, 35));

        tMapel.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tMapel.setText("Mapel");
        tMapel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tMapelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tMapelFocusLost(evt);
            }
        });

        tJamke.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tJamke.setText("Jam ke");
        tJamke.setPreferredSize(new java.awt.Dimension(71, 35));
        tJamke.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tJamkeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tJamkeFocusLost(evt);
            }
        });

        cbGuruPengganti.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        cbGuruPengganti.setMinimumSize(new java.awt.Dimension(72, 35));
        cbGuruPengganti.setPreferredSize(new java.awt.Dimension(72, 35));

        tKeterangan.setColumns(20);
        tKeterangan.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tKeterangan.setRows(5);
        jScrollPane1.setViewportView(tKeterangan);

        tMateri.setColumns(20);
        tMateri.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tMateri.setRows(5);
        jScrollPane2.setViewportView(tMateri);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tJamke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tMapel)
            .addComponent(cbNamaGuru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTGL, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
            .addComponent(tID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbGuruPengganti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tJamke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbGuruPengganti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/icons8-close-20.png"))); // NOI18N
        lClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lClose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(lClose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 744, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lCloseMouseClicked

    
    //Memberi fokus gained agar tulisan di text field kosong saat di klik
    private void tIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tIDFocusGained
        // TODO add your handling code here:
        String ID = tID.getText();
        if(ID.equals("ID Pergantian")){
            tID.setText("");
        }
    }//GEN-LAST:event_tIDFocusGained

    private void tMapelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tMapelFocusGained
        // TODO add your handling code here:
        String mapel = tMapel.getText();
        if(mapel.equals("Mapel")){
            tMapel.setText("");
        }
    }//GEN-LAST:event_tMapelFocusGained

    private void tJamkeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tJamkeFocusGained
        // TODO add your handling code here:
        String jam = tJamke.getText();
        if(jam.equals("Jam ke")){
            tJamke.setText("");
        }
    }//GEN-LAST:event_tJamkeFocusGained

    
    //Memberi fokus lost agar tulisan di text field kosong saat di klik
    //dan kembali lagi jika tidak jadi dinputkan
    private void tIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tIDFocusLost
        // TODO add your handling code here:
        String ID = tID.getText();
        if(ID.equals("")||ID.equals("ID Pergantian")){
            tID.setText("ID Pergantian");
        }
    }//GEN-LAST:event_tIDFocusLost

    private void tMapelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tMapelFocusLost
        // TODO add your handling code here:
        String mapel = tMapel.getText();
        if(mapel.equals("")||mapel.equals("Mapel")){
            tMapel.setText("NMapel");
        }
    }//GEN-LAST:event_tMapelFocusLost

    private void tJamkeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tJamkeFocusLost
        // TODO add your handling code here:
        String jam = tJamke.getText();
        if(jam.equals("")||jam.equals("Jam ke")){
            tJamke.setText("Jam ke");
        }
    }//GEN-LAST:event_tJamkeFocusLost

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
         String idPergantian = tID.getText();

        java.text.SimpleDateFormat formatMulai = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String tanggal = (jTGL.getDate() != null) ? formatMulai.format(jTGL.getDate()) : "";

        String jamKe = tJamke.getText();
        String mapel = tMapel.getText();
        String tugasMateri = tMateri.getText();
        String keterangan = tKeterangan.getText();

        String nipdigantikan = cariNip(cbNamaGuru.getSelectedItem().toString());
        String nipMenggantikan = cariNip(cbGuruPengganti.getSelectedItem().toString());

        String sql = "INSERT INTO pergantian_guru (id_pergantianguru, "
                + "tanggal, "
                + "jam_ke, "
                + "mapel, "
                + "tugas_materi, "
                + "keterangan, "
                + "id_digantikan, "
                + "id_menggantikan) "
                + "VALUES (?,?,?,?,?,?,?,?)";

        try {
            Connection conn = Koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, idPergantian);
            ps.setString(2, tanggal);
            ps.setString(3, jamKe);
            ps.setString(4, mapel);
            ps.setString(5, tugasMateri);
            ps.setString(6, keterangan);
            ps.setString(7, nipdigantikan);
            ps.setString(8, nipMenggantikan);

            ps.execute();

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            pPerG.load_tabel_pengganti();
            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan! : " + e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                tambahPergantianGuru dialog = new tambahPergantianGuru(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bSimpan;
    private javax.swing.JComboBox<String> cbGuruPengganti;
    private javax.swing.JComboBox<String> cbNamaGuru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jTGL;
    private javax.swing.JLabel lClose;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tJamke;
    private javax.swing.JTextArea tKeterangan;
    private javax.swing.JTextField tMapel;
    private javax.swing.JTextArea tMateri;
    // End of variables declaration//GEN-END:variables
}
