/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appabsensismpihidayatuttholibin.view.panelTambahan;

import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class cardQR extends javax.swing.JPanel {

    // Menyimpan gambar QR Code dalam bentuk BufferedImage.
    private BufferedImage qrImage;

    // Menyimpan data siswa.
    private String nama;
    private String nis;
    private String kelas;

    /**
     * Creates new form generateQR
     */
    public cardQR() {
        initComponents();

        borderLengkung(panelQR, "#000000");
    }

    void borderLengkung(JPanel panel, String hexColor) {
        panel.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0),
                Color.decode(hexColor),
                2f,
                20
        ));
    }

    // Mengembalikan panel QR.
    public JPanel getPanelQR() {
        return panelQR;
    }

    // Mengambil nama siswa dari label.
    public String getNama() {
        return lNama.getText();
    }

    // Mengambil NISN siswa dari label.
    public String getNISN() {
        return lNISN.getText();
    }

    // Method untuk menampilkan data siswa dan QR Code ke dalam card.
    public void setData(String nama,
            String nis,
            String kelas,
            String pathQR) {

        // Menampilkan data siswa pada label.
        lNISN.setText(nama);
        lNama.setText(nis);
        lKelas.setText(kelas);

        // Membaca gambar QR Code dari lokasi file.
        ImageIcon icon = new ImageIcon(pathQR);

        // Mengubah ukuran gambar agar sesuai dengan panel.
        Image img = icon.getImage().getScaledInstance(
                265,
                265,
                Image.SCALE_SMOOTH);

        // Menampilkan gambar QR Code pada JLabel.
        lQR.setIcon(new ImageIcon(img));
    }

    // Method untuk mengunduh satu QR Code.
    private void downloadQR() {

        try {

            // Membuka dialog untuk memilih lokasi penyimpanan file.
            JFileChooser chooser = new JFileChooser();
            chooser.setSelectedFile(new File(lNama.getText() + ".png"));

            // Jika pengguna membatalkan proses, method dihentikan.
            if (chooser.showSaveDialog(this)
                    != JFileChooser.APPROVE_OPTION) {
                return;
            }

            // Mengambil file tujuan penyimpanan.
            File file = chooser.getSelectedFile();

            // Membuat gambar baru sesuai ukuran panel QR.
            BufferedImage image = new BufferedImage(
                    panelQR.getWidth(),
                    panelQR.getHeight(),
                    BufferedImage.TYPE_INT_ARGB);

            Graphics2D g2 = image.createGraphics();

            // Menggambar seluruh isi panel QR ke dalam gambar.
            panelQR.printAll(g2);

            g2.dispose();

            // Menyimpan gambar dalam format PNG.
            ImageIO.write(image, "png", file);

            // Menampilkan pesan jika proses berhasil.
            JOptionPane.showMessageDialog(this,
                    "QR berhasil didownload.");

        } catch (Exception e) {

            // Menampilkan pesan jika terjadi kesalahan.
            JOptionPane.showMessageDialog(this,
                    e.getMessage());

        }

    }

    // Method untuk menyimpan QR Code ke file PNG.
    public void simpanQR(File file) {

        try {

            // Mengambil ukuran panel QR.
            int width = panelQR.getWidth();
            int height = panelQR.getHeight();

            // Membuat gambar baru sesuai ukuran panel.
            BufferedImage image = new BufferedImage(
                    width,
                    height,
                    BufferedImage.TYPE_INT_RGB);

            Graphics2D g2 = image.createGraphics();

            // Memberikan warna latar belakang putih.
            g2.setColor(Color.WHITE);
            g2.fillRect(0, 0, width, height);

            // Menggambar seluruh isi panel QR ke gambar.
            panelQR.paint(g2);

            g2.dispose();

            // Menyimpan gambar ke file PNG.
            ImageIO.write(image, "png", file);

        } catch (Exception e) {

            // Menampilkan error pada console jika proses gagal.
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQR = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lNama = new javax.swing.JLabel();
        lNISN = new javax.swing.JLabel();
        lKelas = new javax.swing.JLabel();
        lQR = new javax.swing.JLabel();
        downloadSatuan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        panelQR.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(348, 85));

        lNama.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNama.setText("jLabel1");

        lNISN.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lNISN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNISN.setText("jLabel2");

        lKelas.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lKelas.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lNISN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNISN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lKelas)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lQR.setBackground(new java.awt.Color(255, 255, 255));
        lQR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelQRLayout = new javax.swing.GroupLayout(panelQR);
        panelQR.setLayout(panelQRLayout);
        panelQRLayout.setHorizontalGroup(
            panelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(panelQRLayout.createSequentialGroup()
                        .addComponent(lQR, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelQRLayout.setVerticalGroup(
            panelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lQR, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        downloadSatuan.setBackground(new java.awt.Color(10, 104, 151));
        downloadSatuan.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        downloadSatuan.setForeground(new java.awt.Color(255, 255, 255));
        downloadSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/material-symbols_download-rounded.png"))); // NOI18N
        downloadSatuan.setText("Download");
        downloadSatuan.addActionListener(this::downloadSatuanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadSatuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelQR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void downloadSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadSatuanActionPerformed
        // TODO add your handling code here:
        downloadQR();
    }//GEN-LAST:event_downloadSatuanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadSatuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lKelas;
    private javax.swing.JLabel lNISN;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lQR;
    private javax.swing.JPanel panelQR;
    // End of variables declaration//GEN-END:variables
}
