/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appabsensismpihidayatuttholibin.view.componen;

import appabsensismpihidayatuttholibin.view.formLogin;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class dialogPengguna extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dialogPengguna.class.getName());

    /**
     * Creates new form dialogPengguna
     */
    public dialogPengguna(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        initComponents();
        // Menutup dialog secara otomatis ketika kehilangan fokus.
        addWindowFocusListener(new WindowAdapter() {
            @Override
            public void windowLostFocus(WindowEvent e) {
                dispose();
            }
        });

        // Memberikan border melengkung pada panel utama.
        borderLengkung(panelPengguna, "#000000");
    }

    // Method untuk membuat border panel menjadi melengkung.
    void borderLengkung(JPanel panel, String hexColor) {

        panel.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0), // Mengatur jarak border.
                Color.decode(hexColor), // Mengatur warna border.
                1f, // Ketebalan border.
                20 // Radius sudut border.
        ));
    }

    // Menampilkan data pengguna yang sedang login pada dialog.
    public void setPengguna(String nama, String email, String role) {

        lUsername.setText(nama); // Menampilkan nama pengguna.
        lEmail.setText(email);   // Menampilkan email pengguna.
        lRole.setText(role);     // Menampilkan role pengguna.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPengguna = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lUsername = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lRole = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(359, 173));
        setUndecorated(true);

        panelPengguna.setBackground(new java.awt.Color(255, 255, 255));
        panelPengguna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lUsername.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lUsername.setText("Username");

        lEmail.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        lEmail.setForeground(new java.awt.Color(153, 153, 153));
        lEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEmail.setText("Email");

        lRole.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lRole.setText("Role");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lRole))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        btnHapus.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 0, 0));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/Vector.png"))); // NOI18N
        btnHapus.setText("Keluar");
        btnHapus.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 25, 1, 1, new java.awt.Color(255, 255, 255)));
        btnHapus.setBorderPainted(false);
        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHapus.setIconTextGap(10);
        btnHapus.setMaximumSize(new java.awt.Dimension(154, 37));
        btnHapus.setMinimumSize(new java.awt.Dimension(154, 37));
        btnHapus.setPreferredSize(new java.awt.Dimension(154, 37));
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel3.add(btnHapus);

        javax.swing.GroupLayout panelPenggunaLayout = new javax.swing.GroupLayout(panelPengguna);
        panelPengguna.setLayout(panelPenggunaLayout);
        panelPenggunaLayout.setHorizontalGroup(
            panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPenggunaLayout.setVerticalGroup(
            panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 359, 216);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // Menampilkan dialog konfirmasi logout.
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Apakah anda yakin ingin keluar",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        switch (pilihan) {

            case JOptionPane.YES_OPTION: // Jika pengguna memilih Ya

                dispose(); // Menutup dialog pengguna.
                new formLogin().setVisible(true); // Menampilkan kembali form Login.
                break;

            case JOptionPane.NO_OPTION: // Jika pengguna memilih Tidak
                break;

            default: // Jika dialog ditutup tanpa memilih
                break;
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dialogPengguna dialog = new dialogPengguna(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lRole;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel panelPengguna;
    // End of variables declaration//GEN-END:variables
}
