/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appabsensismpihidayatuttholibin.view;

// Mengimpor dialog profil pengguna.
import appabsensismpihidayatuttholibin.view.componen.dialogPengguna;

// Mengimpor tema FlatLaf berwarna terang.
import com.formdev.flatlaf.FlatLightLaf;

// Mengimpor UIManager untuk mengatur Look and Feel aplikasi.
import javax.swing.UIManager;

// Mengimpor exception jika Look and Feel tidak didukung.
import javax.swing.UnsupportedLookAndFeelException;

// Mengimpor panel-panel utama aplikasi.
import appabsensismpihidayatuttholibin.view.mainPanel.panelDashboard;
import appabsensismpihidayatuttholibin.view.mainPanel.panelAbsensiQR;
import appabsensismpihidayatuttholibin.view.mainPanel.panelAbsensiManual;
import appabsensismpihidayatuttholibin.view.mainPanel.panelLaporan;

// Mengimpor CardLayout untuk perpindahan antar panel.
import java.awt.CardLayout;

// Mengimpor kelas Color untuk pengaturan warna komponen.
import java.awt.Color;

// Mengimpor Point untuk menangani koordinat posisi komponen.
import java.awt.Point;

/**
 *
 * @author ASUS
 */
public class mainFormguru extends javax.swing.JFrame {

    // Menyimpan data pengguna yang sedang login.
    private String nama;
    private String email;
    private String role;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFormguru.class.getName());
    // Objek CardLayout untuk mengatur perpindahan panel.
    private CardLayout cardLayout;

    /**
     * Creates new form mainForm
     */
    public mainFormguru() {
        initComponents(); // Menginisialisasi seluruh komponen GUI.
        inisiasiPanel(); // Memuat seluruh panel ke CardLayout.
        tanggaljam();    // Menjalankan tampilan tanggal dan jam.
    }

    // method untuk memanggil main panel menggunakan cardlayout
    void inisiasiPanel() {
        cardLayout = (CardLayout) panelPerpindahan.getLayout();

        panelPerpindahan.add(new panelDashboard(), "dashboard");
        panelPerpindahan.add(new panelAbsensiQR(), "QR");
        panelPerpindahan.add(new panelAbsensiManual(), "manual");
        panelPerpindahan.add(new panelLaporan(), "laporan");
    }

    // Menampilkan tanggal dan jam secara real-time.
    void tanggaljam() {

        javax.swing.Timer timer = new javax.swing.Timer(1000, (java.awt.event.ActionEvent e) -> {

            // Mengatur format lokal Indonesia.
            java.util.Locale localeIndonesia = new java.util.Locale("id", "ID");

            // Membuat format tampilan tanggal dan waktu.
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(
                    "EEEE, dd MMMM yyyy | HH.mm",
                    localeIndonesia
            );

            // Mengambil waktu saat ini.
            String waktu = sdf.format(new java.util.Date());

            // Menampilkan waktu pada JLabel.
            lTanggalJam.setText(waktu);
        });

        timer.start(); // Menjalankan timer.
    }

    // Menerima data pengguna yang login dan menampilkannya pada form.
    public void setDataUserGuru(String nama, String email, String role) {

        this.nama = nama;     // Menyimpan nama pengguna.
        this.email = email;   // Menyimpan email pengguna.
        this.role = role;     // Menyimpan role pengguna.

        lUsername.setText(nama); // Menampilkan nama pada label.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelSidebar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bDashboard = new javax.swing.JToggleButton();
        bQR = new javax.swing.JToggleButton();
        bManual = new javax.swing.JToggleButton();
        bLaporan = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        panelTengah = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lUsername = new javax.swing.JLabel();
        bProfil = new javax.swing.JButton();
        panelBottom = new javax.swing.JPanel();
        lTanggalJam = new javax.swing.JLabel();
        panelPerpindahan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(39, 81, 103));
        panelSidebar.setPreferredSize(new java.awt.Dimension(270, 900));

        jPanel3.setBackground(new java.awt.Color(39, 81, 103));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        bDashboard.setBackground(new java.awt.Color(39, 81, 103));
        buttonGroup1.add(bDashboard);
        bDashboard.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/material-symbols_dashboard-rounded.png"))); // NOI18N
        bDashboard.setSelected(true);
        bDashboard.setText("Dashboard");
        bDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDashboard.setIconTextGap(10);
        bDashboard.addActionListener(this::bDashboardActionPerformed);
        jPanel3.add(bDashboard);

        bQR.setBackground(new java.awt.Color(39, 81, 103));
        buttonGroup1.add(bQR);
        bQR.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bQR.setForeground(new java.awt.Color(255, 255, 255));
        bQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/boxicons_qr-scan (2).png"))); // NOI18N
        bQR.setText("Absensi QR");
        bQR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bQR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bQR.setIconTextGap(10);
        bQR.addActionListener(this::bQRActionPerformed);
        jPanel3.add(bQR);

        bManual.setBackground(new java.awt.Color(39, 81, 103));
        buttonGroup1.add(bManual);
        bManual.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bManual.setForeground(new java.awt.Color(255, 255, 255));
        bManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ic_twotone-class (2).png"))); // NOI18N
        bManual.setText("Absensi Manual");
        bManual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bManual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bManual.setIconTextGap(10);
        bManual.addActionListener(this::bManualActionPerformed);
        jPanel3.add(bManual);

        bLaporan.setBackground(new java.awt.Color(39, 81, 103));
        buttonGroup1.add(bLaporan);
        bLaporan.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bLaporan.setForeground(new java.awt.Color(255, 255, 255));
        bLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/lsicon_management-outline (2).png"))); // NOI18N
        bLaporan.setText("Laporan");
        bLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLaporan.setIconTextGap(10);
        bLaporan.addActionListener(this::bLaporanActionPerformed);
        jPanel3.add(bLaporan);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ix_user-profile (1).png"))); // NOI18N

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelTengah.setBackground(new java.awt.Color(201, 223, 237));
        panelTengah.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(246, 250, 253));
        Header.setPreferredSize(new java.awt.Dimension(1300, 70));
        Header.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(246, 250, 253));

        jPanel2.setBackground(new java.awt.Color(246, 250, 253));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        lUsername.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lUsername.setText("Admin");
        lUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 20, 1, 1, new java.awt.Color(255, 255, 255)));

        bProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/icons8-expand-arrow-30.png"))); // NOI18N
        bProfil.setBorderPainted(false);
        bProfil.addActionListener(this::bProfilActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(bProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(948, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Header.add(jPanel1, java.awt.BorderLayout.CENTER);

        panelTengah.add(Header, java.awt.BorderLayout.PAGE_START);

        panelBottom.setBackground(new java.awt.Color(246, 250, 253));
        panelBottom.setPreferredSize(new java.awt.Dimension(1330, 50));

        lTanggalJam.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lTanggalJam.setText("Day, dd Month yyyy | 00:00");

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBottomLayout.createSequentialGroup()
                .addContainerGap(1386, Short.MAX_VALUE)
                .addComponent(lTanggalJam, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTanggalJam, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTengah.add(panelBottom, java.awt.BorderLayout.PAGE_END);

        panelPerpindahan.setBackground(new java.awt.Color(201, 223, 237));
        panelPerpindahan.setLayout(new java.awt.CardLayout());
        panelTengah.add(panelPerpindahan, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "dashboard");
    }//GEN-LAST:event_bDashboardActionPerformed

    private void bQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQRActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "QR");
    }//GEN-LAST:event_bQRActionPerformed

    private void bManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManualActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "manual");
    }//GEN-LAST:event_bManualActionPerformed

    private void bLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "laporan");
    }//GEN-LAST:event_bLaporanActionPerformed

    private void bProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProfilActionPerformed
        // TODO add your handling code here:
        // Membuat objek dialog profil pengguna dengan form utama sebagai parent.
        dialogPengguna menu = new dialogPengguna(this, true);

        // Mengirim data pengguna yang sedang login ke dialog.
        menu.setPengguna(nama, email, role);

        // Menampilkan JDialog tepat di bawah tombol Profil.
        Point p = bProfil.getLocationOnScreen();             // Mengambil posisi tombol Profil di layar.
        int x = p.x + bProfil.getWidth() - menu.getWidth();  // Mengatur posisi horizontal dialog.
        int y = 5 + p.y + bProfil.getHeight();               // Mengatur posisi vertikal dialog.
        menu.setLocation(x, y);                              // Menetapkan posisi dialog.
        menu.setVisible(true);                               // Menampilkan dialog.
    }//GEN-LAST:event_bProfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("ToggleButton.selectedBackground", new Color(0, 128, 195));
            UIManager.put("Button.arc", 20);
            UIManager.put("ToggleButton.arc", 20);
            UIManager.put("Button.arc", 20);
            UIManager.put("Button.borderwidht", 0);
            UIManager.put("TextComponent.arc", 20);
            UIManager.put("Component.borderwidht", 0);
            UIManager.put("Component.focusWidth", 0);
            UIManager.put("Component.innerFocuswidht", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFormguru().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JToggleButton bDashboard;
    private javax.swing.JToggleButton bLaporan;
    private javax.swing.JToggleButton bManual;
    private javax.swing.JButton bProfil;
    private javax.swing.JToggleButton bQR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lTanggalJam;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelPerpindahan;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelTengah;
    // End of variables declaration//GEN-END:variables
}
